export type backgroundColor =
  | 'danger'
  | 'dark'
  | 'default'
  | 'info'
  | 'light'
  | 'primary'
  | 'secondary'
  | 'success'
  | 'warning';
export type backgroundColorType = { backgroundColor?: backgroundColor };
export type buttonColor = 
  | 'amber'
  | 'blue-grey'
  | 'blue'
  | 'brown'
  | 'cyan'
  | 'danger'
  | 'dark-green'
  | 'dark'
  | 'deep-orange'
  | 'deep-purple'
  | 'default'
  | 'elegant'
  | 'green'
  | 'grey'
  | 'indigo'
  | 'info'
  | 'light-blue'
  | 'light-green'
  | 'light'
  | 'lime'
  | 'mdb-color'
  | 'orange'
  | 'pink'
  | 'primary'
  | 'purple'
  | 'secondary'
  | 'success'
  | 'unique'
  | 'warning'
  | 'red'
  | 'yellow';

export type classNameType = { className?: string };
export type color =
  | 'amber'
  | 'blue-grey'
  | 'blue'
  | 'brown'
  | 'cyan'
  | 'danger'
  | 'dark'
  | 'deep-orange'
  | 'deep-purple'
  | 'default'
  | 'green'
  | 'grey'
  | 'indigo'
  | 'info'
  | 'light-blue'
  | 'light-green'
  | 'light'
  | 'lime'
  | 'mdb-color'
  | 'muted'
  | 'orange'
  | 'pink'
  | 'primary'
  | 'purple'
  | 'red'
  | 'secondary'
  | 'success'
  | 'teal'
  | 'warning'
  | 'yellow';
export type colorType = { color?: color };
export type colSizeTypes = {
  size?:
    | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12'
    | 'auto';
  xs?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
  sm?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
  md?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
  lg?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
  xl?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
};
export type gradient =
  | 'amy-crisp'
  | 'aqua'
  | 'blue'
  | 'cloudy-knoxville'
  | 'deep-blue'
  | 'dusty-grass'
  | 'frozen-dreams'
  | 'heavy-rain'
  | 'juicy-peach'
  | 'lady-lips'
  | 'mean-fruit'
  | 'morpheus-den'
  | 'near-moon'
  | 'night-fade'
  | 'peach'
  | 'purple'
  | 'rainy-ashville'
  | 'rare-wind'
  | 'ripe-malinka'
  | 'spring-warmth'
  | 'sunny-morning'
  | 'tempting-azure'
  | 'warm-flame'
  | 'winter-neva'
  | 'young-passion';
export type gradientType = { gradient?: gradient };
export type iconSize =
  | 'lg'
  | '1x'
  | '2x'
  | '3x'
  | '4x'
  | '5x'
  | '6x'
  | '7x'
  | '8x'
  | '9x'
  | '10x';
